# Generated by Django 6.0 on 2025-12-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='nul', max_length=200),
            preserve_default=False,
        ),
    ]
