# Generated by Django 5.2.9 on 2025-12-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_desk_id_alter_sale_id_alter_saleitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
