# Generated by Django 5.2.9 on 2026-01-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='value',
        ),
        migrations.AddField(
            model_name='sale',
            name='desk_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Crédito'), (2, 'Débito'), (3, 'Pix'), (4, 'Dinheiro')], null=True),
        ),
        migrations.DeleteModel(
            name='Desk',
        ),
    ]
